name: Deploy to VPS

on:
  push:
    branches:
      - master  # или имя вашего рабочего ветви

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: 79.174.91.122
        username: root
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd ledovod-web
          git reset --hard
          git pull origin master --force
          npm install
          npm run-script build
          pm2 reload ledovod-web
